---
packageRules:
- package: "com.github.mxenabled.binks"
  rules:
    major:
      maxDiff: 0
      requireLatest: false
    minor:
      maxDiff: 0
      requireLatest: false
    micro:
      maxDiff: 0
      requireLatest: false
- package: "com.github.mxenabled.coppuccino:com.github.mxenabled.coppuccino.gradle.plugin"
  rules: {}
  suppressUntil: "2026-03-02"
- package: "com.github.mxenabled.vogue:com.github.mxenabled.vogue.gradle.plugin"
  rules: {}
  suppressUntil: "2026-03-02"
