import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
  id "com.github.mxenabled.coppuccino" version "8.+"
  id "com.github.mxenabled.vogue" version "5.+"
  id "groovy"
  id "java-gradle-plugin"
  id "maven-publish"
  id "org.jetbrains.kotlin.jvm" version "2.3.0"
}

group "com.mx.binks"
version "4.0.0" // x-release-please-version

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(21)
  }
}

kotlin {
  compilerOptions {
    jvmTarget = JvmTarget.JVM_21
  }
}

coppuccino {
  kotlin { enabled = true }
}

repositories {
  mavenCentral()
  mavenLocal()
  gradlePluginPortal()
  maven { url "https://jitpack.io" }
}

dependencies {
  implementation "com.lordcodes.turtle:turtle:0.7.0" // Provides git and commandline interaction API

  testImplementation "org.mockito:mockito-core:[5.0,6.0)"
  testImplementation "org.spockframework:spock-core:2.4-M6-groovy-4.0"
  testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test { useJUnitPlatform() }

gradlePlugin {
  plugins {
    binksPlugin {
      id = group
      implementationClass = "com.mx.binks.BinksPlugin"
    }
    binksJitPackPlugin {
      id = "com.github.mxenabled.binks"
      implementationClass = "com.mx.binks.BinksPlugin"
    }
  }
}

wrapper {
  gradleVersion = "9.5.1"
  distributionType = Wrapper.DistributionType.ALL
}
